'use strict';

export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const CALCULATE_EXPRESSION = 'CALCULATE_EXPRESSION';
export const SET_VALUE = 'SET_VALUE';
export const SWITCH_TIME_FORMAT = 'SWITCH_TIME_FORMAT';
export const SWITCH_TIME_TAB = 'SWITCH_TIME_TAB';